# Generated by Django 6.0.7 on 2026-07-27 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_video_url'),
        ('users', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_at', models.DateTimeField(default=django.utils.timezone.now,
                                                    verbose_name='Date/Time of payment')),
                ('payment_amount', models.PositiveIntegerField(default=0, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('Cash', 'Наличные'), ('Transfer', 'Перевод')],
                                                    default='Transfer')),
                ('payed_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('payed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('user', models.ForeignKey(help_text='Пользователь, котопый оплатил курс',
                                           on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL,
                                           verbose_name='User that payd for the course')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_at'],
            },
        ),
    ]
