# Generated by Django 6.0.7 on 2026-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payments_payed_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
