# Generated by Django 6.0.7 on 2026-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payments_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Ожидает оплаты'),
                                            ('Paid', 'Оплачен'), ('Cancelled', 'Отменён')],
                                   default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
