# Generated by Django 6.0.7 on 2026-07-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название курса', max_length=100, verbose_name='Course name')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='img/course_preview/')),
                ('description', models.TextField(blank=True, help_text='Описание курса', null=True, verbose_name='Course description')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название урока', max_length=100, verbose_name='Lesson name')),
                ('description', models.TextField(blank=True, help_text='Описание урока', null=True, verbose_name='Lesson description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='img/lesson_preview/')),
                ('video_url', models.CharField(help_text='Ссылка на видео', max_length=100, verbose_name='Lesson video link')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['name'],
            },
        ),
    ]
