# Generated by Django 6.0.7 on 2026-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, help_text='Ссылка на видео', max_length=100,
                                   null=True, verbose_name='Lesson video link'),
        ),
    ]
