# Generated by Django 6.0.7 on 2026-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_courseupdatesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prise',
            field=models.IntegerField(default=100, verbose_name='Course price'),
            preserve_default=False,
        ),
    ]
