# Generated by Django 6.0.7 on 2026-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_course_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prise',
            field=models.IntegerField(default=200, verbose_name='Course prise'),
            preserve_default=False,
        ),
    ]
