# Generated by Django 6.0.7 on 2026-08-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_lesson_prise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='prise',
            new_name='price',
        ),
    ]
