# Generated by Django 6.0.7 on 2026-08-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_rename_prise_lesson_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prise',
            new_name='price',
        ),
    ]
