# Generated by Django 6.0.7 on 2026-08-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_rename_prise_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(verbose_name='Course price'),
        ),
    ]
